[theme]
base = "light"
primaryColor = "#2a78d6"
backgroundColor = "#fcfcfb"
secondaryBackgroundColor = "#f1f0ec"
textColor = "#0b0b0b"
borderColor = "#e1e0d9"
redColor = "#d03b3b"
orangeColor = "#ec835a"
yellowColor = "#fab219"
greenColor = "#0ca30c"
